
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

SKIA_FILES :=\
core/Sk64.cpp \
core/SkAAClip.cpp \
core/SkAdvancedTypefaceMetrics.cpp \
core/SkAlphaRuns.cpp \
core/SkBitmap.cpp \
core/SkBitmap_scroll.cpp \
core/SkBitmapProcShader.cpp \
core/SkBitmapProcState.cpp \
core/SkBitmapProcState_matrixProcs.cpp \
core/SkBitmapSampler.cpp \
core/SkBlitMask_D32.cpp \
core/SkBlitRow_D16.cpp \
core/SkBlitRow_D32.cpp \
core/SkBlitRow_D4444.cpp \
core/SkBlitter.cpp \
core/SkBlitter_4444.cpp \
core/SkBlitter_A1.cpp \
core/SkBlitter_A8.cpp \
core/SkBlitter_ARGB32.cpp \
core/SkBlitter_RGB16.cpp \
core/SkBlitter_Sprite.cpp \
core/SkBuffer.cpp \
core/SkCanvas.cpp \
core/SkChunkAlloc.cpp \
core/SkClipStack.cpp \
core/SkColor.cpp \
core/SkColorFilter.cpp \
core/SkColorTable.cpp \
core/SkComposeShader.cpp \
core/SkConcaveToTriangles.cpp \
core/SkConfig8888.cpp \
core/SkCordic.cpp \
core/SkCubicClipper.cpp \
core/SkData.cpp \
core/SkDebug.cpp \
core/SkDeque.cpp \
core/SkDevice.cpp \
core/SkDeviceProfile.cpp \
core/SkDither.cpp \
core/SkDraw.cpp \
core/SkEdge.cpp \
core/SkEdgeBuilder.cpp \
core/SkEdgeClipper.cpp \
core/SkFilterProc.cpp \
core/SkFlate.cpp \
core/SkFlattenable.cpp \
core/SkFloat.cpp \
core/SkFloatBits.cpp \
core/SkFontHost.cpp \
core/SkGeometry.cpp \
core/SkGlyphCache.cpp \
core/SkGraphics.cpp \
core/SkInstCnt.cpp \
core/SkLineClipper.cpp \
core/SkMallocPixelRef.cpp \
core/SkMask.cpp \
core/SkMaskFilter.cpp \
core/SkMath.cpp \
core/SkMatrix.cpp \
core/SkMemory_stdlib.cpp \
core/SkMetaData.cpp \
core/SkMMapStream.cpp \
core/SkOrderedReadBuffer.cpp \
core/SkOrderedWriteBuffer.cpp \
core/SkPackBits.cpp \
core/SkPaint.cpp \
core/SkPath.cpp \
core/SkPathEffect.cpp \
core/SkPathHeap.cpp \
core/SkPathMeasure.cpp \
core/SkPicture.cpp \
core/SkPictureFlat.cpp \
core/SkPicturePlayback.cpp \
core/SkPictureRecord.cpp \
core/SkPixelRef.cpp \
core/SkPoint.cpp \
core/SkProcSpriteBlitter.cpp \
core/SkPtrRecorder.cpp \
core/SkQuadClipper.cpp \
core/SkRasterClip.cpp \
core/SkRasterizer.cpp \
core/SkRect.cpp \
core/SkRefCnt.cpp \
core/SkRefDict.cpp \
core/SkRegion.cpp \
core/SkRegion_path.cpp \
core/SkRegion_rects.cpp \
core/SkScalar.cpp \
core/SkScalerContext.cpp \
core/SkScan.cpp \
core/SkScan_Antihair.cpp \
core/SkScan_AntiPath.cpp \
core/SkScan_Hairline.cpp \
core/SkScan_Path.cpp \
core/SkShader.cpp \
core/SkShape.cpp \
core/SkSpriteBlitter_ARGB32.cpp \
core/SkSpriteBlitter_RGB16.cpp \
core/SkStream.cpp \
core/SkString.cpp \
core/SkStroke.cpp \
core/SkStrokerPriv.cpp \
core/SkTLS.cpp \
core/SkTSearch.cpp \
core/SkTypeface.cpp \
core/SkTypefaceCache.cpp \
core/SkUnPreMultiply.cpp \
core/SkUtils.cpp \
core/SkUtilsArm.cpp \
core/SkWriter32.cpp \
core/SkXfermode.cpp \
images/bmpdecoderhelper.cpp \
images/SkFDStream.cpp \
images/SkFlipPixelRef.cpp \
images/SkImageDecoder.cpp \
images/SkImageDecoder_Factory.cpp \
images/SkImageDecoder_libpng.cpp \
images/SkImageEncoder.cpp \
images/SkImageEncoder_Factory.cpp \
images/SkImageRef.cpp \
images/SkImageRef_GlobalPool.cpp \
images/SkImageRefPool.cpp \
images/SkMovie.cpp \
images/SkPageFlipper.cpp \
images/SkScaledBitmapSampler.cpp \
utils/SkBase64.cpp \
utils/SkBitSet.cpp \
utils/SkBoundaryPatch.cpp \
utils/SkCamera.cpp \
utils/SkCubicInterval.cpp \
utils/SkCullPoints.cpp \
utils/SkDeferredCanvas.cpp \
utils/SkDumpCanvas.cpp \
utils/SkInterpolator.cpp \
utils/SkJSON.cpp \
utils/SkLayer.cpp \
utils/SkMatrix44.cpp \
utils/SkMeshUtils.cpp \
utils/SkNinePatch.cpp \
utils/SkNullCanvas.cpp \
utils/SkNWayCanvas.cpp \
utils/SkOSFile.cpp \
utils/SkParse.cpp \
utils/SkParseColor.cpp \
utils/SkParsePath.cpp \
utils/SkProxyCanvas.cpp \
utils/SkSfntUtils.cpp \
utils/SkThreadUtils_pthread.cpp \
utils/SkThreadUtils_pthread_other.cpp \
utils/SkUnitMappers.cpp \
effects/Sk1DPathEffect.cpp \
effects/Sk2DPathEffect.cpp \
effects/SkArithmeticMode.cpp \
effects/SkAvoidXfermode.cpp \
effects/SkBitmapCache.cpp \
effects/SkBlurDrawLooper.cpp \
effects/SkBlurImageFilter.cpp \
effects/SkBlurMask.cpp \
effects/SkBlurMaskFilter.cpp \
effects/SkClampRange.cpp \
effects/SkColorFilters.cpp \
effects/SkColorMatrix.cpp \
effects/SkColorMatrixFilter.cpp \
effects/SkCornerPathEffect.cpp \
effects/SkDashPathEffect.cpp \
effects/SkDiscretePathEffect.cpp \
effects/SkEmbossMask.cpp \
effects/SkEmbossMaskFilter.cpp \
effects/SkGradientShader.cpp \
effects/SkGroupShape.cpp \
effects/SkKernel33MaskFilter.cpp \
effects/SkLayerDrawLooper.cpp \
effects/SkLayerRasterizer.cpp \
effects/SkLightingImageFilter.cpp \
effects/SkMorphologyImageFilter.cpp \
effects/SkPaintFlagsDrawFilter.cpp \
effects/SkPixelXorXfermode.cpp \
effects/SkPorterDuff.cpp \
effects/SkRectShape.cpp \
effects/SkStippleMaskFilter.cpp \
effects/SkTableColorFilter.cpp \
effects/SkTableMaskFilter.cpp \
effects/SkTestImageFilters.cpp \
effects/SkTransparentShader.cpp \
ports/SkDebug_android.cpp \
ports/SkFontDescriptor.cpp \
ports/SkFontHost_simple.cpp \
ports/SkFontHost_FreeType.cpp \
ports/SkFontHost_gamma.cpp \
ports/SkFontHost_sandbox_none.cpp \
ports/SkFontHost_tables.cpp \
ports/SkGlobalInitialization_default.cpp \
ports/SkMemory_malloc.cpp \
ports/SkOSFile_stdio.cpp \
ports/SkThread_pthread.cpp \
ports/SkTime_Unix.cpp \
ports/SkXMLParser_empty.cpp \
opts/opts_check_arm.cpp \
opts/memset.arm.S \
opts/SkBitmapProcState_opts_arm.cpp \
opts/SkBlitRow_opts_arm.cpp \
gpu/android/GrGLCreateNativeInterface_android.cpp \
gpu/android/SkNativeGLContext_android.cpp \
gpu/effects/GrConvolutionEffect.cpp \
gpu/effects/GrGradientEffects.cpp \
gpu/effects/GrMorphologyEffect.cpp \
gpu/gl/debug/GrBufferObj.cpp \
gpu/gl/debug/GrDebugGL.cpp \
gpu/gl/debug/GrFrameBufferObj.cpp \
gpu/gl/debug/GrGLCreateDebugInterface.cpp \
gpu/gl/debug/GrProgramObj.cpp \
gpu/gl/debug/GrShaderObj.cpp \
gpu/gl/debug/GrTextureObj.cpp \
gpu/gl/debug/GrTextureUnitObj.cpp \
gpu/gl/debug/SkDebugGLContext.cpp \
gpu/gl/GrGLCaps.cpp \
gpu/gl/GrGLContextInfo.cpp \
gpu/gl/GrGLCreateNativeInterface_none.cpp \
gpu/gl/GrGLCreateNullInterface.cpp \
gpu/gl/GrGLDefaultInterface_native.cpp \
gpu/gl/GrGLDefaultInterface_none.cpp \
gpu/gl/GrGLIndexBuffer.cpp \
gpu/gl/GrGLInterface.cpp \
gpu/gl/GrGLPath.cpp \
gpu/gl/GrGLProgram.cpp \
gpu/gl/GrGLProgramStage.cpp \
gpu/gl/GrGLRenderTarget.cpp \
gpu/gl/GrGLShaderBuilder.cpp \
gpu/gl/GrGLSL.cpp \
gpu/gl/GrGLStencilBuffer.cpp \
gpu/gl/GrGLTexture.cpp \
gpu/gl/GrGLUtil.cpp \
gpu/gl/GrGLVertexBuffer.cpp \
gpu/gl/GrGpuGL.cpp \
gpu/gl/GrGpuGL_program.cpp \
gpu/gl/GrGpuGL_unittest.cpp \
gpu/gl/SkGLContext.cpp \
gpu/gl/SkNullGLContext.cpp \
gpu/GrAAConvexPathRenderer.cpp \
gpu/GrAAHairLinePathRenderer.cpp \
gpu/GrAARectRenderer.cpp \
gpu/GrAddPathRenderers_default.cpp \
gpu/GrAddPathRenderers_none.cpp \
gpu/GrAllocPool.cpp \
gpu/GrAtlas.cpp \
gpu/GrBufferAllocPool.cpp \
gpu/GrClip.cpp \
gpu/GrClipMaskManager.cpp \
gpu/GrContext.cpp \
gpu/GrCustomStage.cpp \
gpu/GrDefaultPathRenderer.cpp \
gpu/GrDrawTarget.cpp \
gpu/GrGpu.cpp \
gpu/GrGpuFactory.cpp \
gpu/GrInOrderDrawBuffer.cpp \
gpu/GrMatrix.cpp \
gpu/GrMemory.cpp \
gpu/GrMemoryPool.cpp \
gpu/GrPathRenderer.cpp \
gpu/GrPathRendererChain.cpp \
gpu/GrPathUtils.cpp \
gpu/GrRectanizer.cpp \
gpu/GrRectanizer_fifo.cpp \
gpu/GrRenderTarget.cpp \
gpu/GrResource.cpp \
gpu/GrResourceCache.cpp \
gpu/GrSoftwarePathRenderer.cpp \
gpu/GrStencil.cpp \
gpu/GrStencilAndCoverPathRenderer.cpp \
gpu/GrStencilBuffer.cpp \
gpu/GrSurface.cpp \
gpu/GrSWMaskHelper.cpp \
gpu/GrTextContext.cpp \
gpu/GrTextStrike.cpp \
gpu/GrTexture.cpp \
gpu/SkGpuCanvas.cpp \
gpu/SkGpuDevice.cpp \
gpu/SkGr.cpp \
gpu/SkGrFontScaler.cpp \
gpu/SkGrPixelRef.cpp \
gpu/SkGrTexturePixelRef.cpp

LOCAL_ARM_MODE := arm

LOCAL_SRC_FILES  := $(addprefix ../$(DEPS_PATH)/skia/src/,$(SKIA_FILES)) #FontHostConfiguration_android.cpp
LOCAL_C_INCLUDES := $(COMMON_INCLUDES)

LOCAL_MODULE := libskia
LOCAL_LDLIBS := -lz -llog
LOCAL_CFLAGS := -O2

include $(BUILD_STATIC_LIBRARY)
